### PR TITLE
fix(execution): handle errors w/ passing scores better

### PR DESCRIPTION
**Pull request by erikmunson**
Sometimes things go wrong during cleanup and mark the kayenta stage TERMINAL even though the score passed. There was some logic in the transformer that would check `stage.isFailed` and add the canary score explanation message to the list of exceptions, which led to weird UX where you'd get an 'exception' that said `Final canary score 100.0 met or exceeded the pass score threshold.` in red.

I decided to switch that up so we check the score itself and whether it was above the marginal threshold in applicable spots, which also includes the color of the big score in the stage summary and the little label on the graph.

Also fixed a case where when the first `runCanary` stage fails it doesn't update the `canaryScoreMessage` on it's ancestor stage. Will probably also look at that from the backend angle too.

### CODE REVIEW

**Comment by erikmunson** [comment]
cc @asher

**Comment by erikmunson** [comment]
indeed — this is more of a 'why is the UI telling me things that seem weird?' kind of experience. you get a few TERMINAL cleanup stages appearing in the list with whatever exceptions are relevant, so provided you're not confused about what the stage is trying to do conceptually it's straightforward to figure out that the UI is just being weird and the analysis went ok (even though the scores right now are red since we were using the stage status to color them).

You'll see me fixing more of these small quality-of-life bugs in the stage UI as we begin to roll it out to more folks internally and get feedback — this particular case happened as we were setting up a canary stage for our internal clouddriver deploy pipeline.

**Comment by erikmunson** [comment]
for posterity's sake, i'm actually just going to show before/after shots. Before:

screen shot 2019-03-06 at 12 01 39 pm

screen shot 2019-03-06 at 12 01 31 pm

And after:

screen shot 2019-03-06 at 12 00 32 pm

**Comment by maggieneterval** [comment]
Nice, it's 100x better now :+1:

**Pull request merged**
