### PR TITLE
feat(metrics): Add support for nanStrategy and criticality flag

### PR DESCRIPTION
**Pull request by erikmunson**
- Totally open to wording / presentational changes on any of this, I'm pretty new to kayenta-land and don't have much context on terms, user expectations, etc.
- `nanStrategy` defaults to no value, which we treat as `remove` on the backend. This leaves open other defaults in the future. I went back and forth on whether it should be 'Default, Replace, Remove' or just 'Remove, Replace' (which would mean choosing `Remove` wouldn't save a value to the configuration), and settled on the former for now since it's clearer what you're agreeing to.
- Since `critical` is also optional, I chose to omit it from the configuration when false to leave more flexibility on future defaults if needed. Happy to change that if people would prefer we explicitly save a false value.

configure metric modal

cc @skandragon @christophersanson

### CODE REVIEW

**Comment by duftler** [comment]
@csanden

**Comment by duftler** [comment]
Can you also please add a tooltip for the NaN Strategy as non-Atlas users may not be familiar with the issue that's being addressed?

**Comment by erikmunson** [comment]
@danielpeach I actually thought about leaving out that label, but given the left-rail label layout that's currently applied here I didn't particularly like the scanning/reading flow without it when I tested it out. I'd be more apt to go label-less if we were doing vertically stacked labels.

**Comment by danielpeach** [comment]
Sure, sounds good to me.

**Comment by duftler** [comment]
I'm not sure where the NaN strategy setting is used, so I don't know if others would use it as well. Is it intended to be something passed along with the queries to atlas, or passed to the cleaning phase of the judge, or something else? If it ends up relevant only for Atlas, I'd rather we don't render it for non-Atlas configurations.

**Comment by erikmunson** [comment]
After syncing up w/ @skandragon, I'm gonna leave this as multi-metric since we do the relevant transformation outside of Atlas itself and choosing a strategy *may* be helpful for other metric sources as well.

Added some help text which should clarify usage for the uninitiated.

**Pull request merged**
