### PR TITLE
chore(deps): upgrade prettier, format files

### PR DESCRIPTION
**Pull request by erikmunson**
The version of prettier that was running was too old to understand the newer typescript features like optional chaining, this does an upgrade to the latest version and formats all the files. also moved code from a recent PR that exposed this issue to use optional chaining.

### CODE REVIEW

**Comment by christopherthielen** [comment]
oh lordy, what have you done?

**Comment by erikmunson** [comment]
wait did i do something wrong??? 😆 😱

**Comment by erikmunson** [comment]
oh actually i do see here that this bumped from 1.x to 2.x, though it doesn't seem to have broken anything. is that going to cause problems bringing it into deck/deck-nflx? I didn't think it would since it's a dev dependency

**Comment by christopherthielen** [comment]
the commit message is incorrect.
See: 

- https://github.com/spinnaker/deck/pull/5754
- https://github.com/spinnaker/deck/pull/5755
- https://github.com/spinnaker/deck/pull/5802
- https://github.com/spinnaker/deck/pull/6600

**Comment by erikmunson** [comment]
this is one of the worst mistakes of my professional career. i feel shame.

**Pull request merged**
